spring.application.name=telegrambot
spring.ai.google.genai.api-key=AQ.Ab8RN6Jc1uXYSpz4MH9dyNUfbNwday725uh3rK4zKZA3aT1sPw
spring.ai.google.genai.chat.model=gemini-2.5-flash
# Keeping temperature 0 makes the model factual and consistent for data extraction
spring.ai.google.genai.chat.temperature=0.0
